services:
  nginx:
    build:
      context: ${NGINX_CONTEXT}
      dockerfile: Dockerfile
    image: nginx:inception
    container_name: nginx
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - wordpress_data:${WP_VOLUME}
    networks:
      - inception_network
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  wordpress:
    build:
      context: ${WORDPRESS_CONTEXT}
      dockerfile: Dockerfile
    image: wordpress:inception
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception_network
    volumes:
      - wordpress_data:${WP_VOLUME}
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_LOGIN: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_ROLE: ${WP_USER_ROLE}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  mariadb:
    build:
      context: ${MARIADB_CONTEXT}
      dockerfile: Dockerfile
    image: mariadb:inception
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception_network
    volumes:
      - mariadb_data:${DB_VOLUME}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost --user=root --password=$$(cat /run/secrets/db_root_password)",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  inception_network:
    driver: bridge

secrets:
  db_root_password:
    file: ${SECRET_DB_ROOT_PASS_FILE}
  db_password:
    file: ${SECRET_DB_USER_PASS_FILE}
  wp_admin_password:
    file: ${SECRET_WP_ADMIN_PASS_FILE}
  wp_user_password:
    file: ${SECRET_WP_USER_PASS_FILE}

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}wordpress
      o: bind
